### PR TITLE
README: detail the variations from Tanzil's text

### PR DESCRIPTION
**Pull request by mustafa0x**
Tanzil's text is the *de facto* standard, so it'd be helpful to know what variations the text here has.

I'm not sure if I covered everything, but I doubt it.

### CODE REVIEW

**Comment by mustafa0x** [comment]
I'd also appreciate knowing the reasoning behind "Use U+06E4 (Small High Madda) instead of U+0653 (Maddah Above)".

**Comment by khaledhosny** [comment]
Since this text was not based on Tanzil’s in any way, I don’t see the need for explicit reference. Last I checked, Tanzil text did not strictly fully any established Quranic orthography.

U+06E4 is used because it was encoded specifically for use in Quran (I had to dig this up until I found the relevant Unicode proposal), while U+0653 is a form of hamza which is not how madda is used for in Quran. Furher more, U+0622 آ is canonically equivalent to  U+0627 ا + U+0653, so applying Unicode normalization to the text where U+0653 is used for Quranic mad will cause U+0627+U+0653 to be converted into U+0622, losing any semantic distinction.

**Comment by mustafa0x** [comment]
The idea was that since Tanzil is the most popular text, people might be interested as to what the differences are — I was. However maybe that's better discussed elsewhere.

Nice to know about U+06E4!

**Comment by khaledhosny** [comment]
I don’t know about the popularity, but what reason to have this repo is that all publicly available digital Quran texts I can find were full of issues.

**Pull request closed without merging**
